version: '3.4'

services:
  app:
    ports:
      - 80:80
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    build:
      context: .
      dockerfile: .docker/php-apache/Dockerfile
    volumes:
      - docker-app-sync:/var/www/html
volumes:
  docker-app-sync:
    external: true